# Tags: 4.8-20211109-windowsservercore-ltsc2016, 4.8-windowsservercore-ltsc2016
FROM mcr.microsoft.com/dotnet/framework/wcf:4.8-20211109-windowsservercore-ltsc2016
FROM mcr.microsoft.com/dotnet/framework/wcf:4.8-windowsservercore-ltsc2016
