# Tags: 4.8-20211109-windowsservercore-2004, 4.8-windowsservercore-2004
FROM mcr.microsoft.com/dotnet/framework/wcf:4.8-20211109-windowsservercore-2004
FROM mcr.microsoft.com/dotnet/framework/wcf:4.8-windowsservercore-2004
