# Tags: 4.8-20211109-windowsservercore-ltsc2022, 4.8-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/framework/wcf:4.8-20211109-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/framework/wcf:4.8-windowsservercore-ltsc2022
