# Tags: 4.6.2-windowsservercore-ltsc2016, 4.6.2-20211109-windowsservercore-ltsc2016
FROM mcr.microsoft.com/dotnet/framework/wcf:4.6.2-windowsservercore-ltsc2016
FROM mcr.microsoft.com/dotnet/framework/wcf:4.6.2-20211109-windowsservercore-ltsc2016
