# Tags: 4.7.1-windowsservercore-ltsc2016, 4.7.1-20211109-windowsservercore-ltsc2016
FROM mcr.microsoft.com/dotnet/framework/wcf:4.7.1-windowsservercore-ltsc2016
FROM mcr.microsoft.com/dotnet/framework/wcf:4.7.1-20211109-windowsservercore-ltsc2016
